local plugin = require("floaterm")
local config = require("floaterm.config")

describe("setup", function()
  it("works with default", function()
    assert(plugin.setup() == nil, "setup with no param should return nil")
  end)

  it("works with custom var", function()
    assert(plugin.setup({ width = 0.8, height = 0.8 }) == nil, "setup with custom param should return nil")
  end)

  it("does not work with invalid opt", function()
    local status, err = pcall(function()
      plugin.setup({ invalid_opt = "invalid" })
    end)
    assert(not status, "setup with invalid param should fail")
    assert(err:find("Invalid configuration key"), "Error message should contain 'Invalid configuration key'")
  end)
end)

describe("register_terminal", function()
  it("creates a terminal", function()
    local terminal = plugin.register_terminal("test_term", "<leader>tt")
    assert(terminal ~= nil, "register_terminal should return a terminal object")
    assert(terminal.id == "test_term", "terminal id should match")
    assert(terminal.cmd == nil, "terminal should not have a cmd")
  end)

  it("returns existing terminal if id already exists", function()
    local term1 = plugin.register_terminal("duplicate_term", "<leader>td")
    local term2 = plugin.register_terminal("duplicate_term", "<leader>td2")
    assert(term1 == term2, "should return the same terminal object")
  end)
end)

describe("register_app", function()
  it("creates an app with a command", function()
    local app = plugin.register_app("test_app", "<leader>ta", "echo test")
    assert(app ~= nil, "register_app should return a terminal object")
    assert(app.id == "test_app", "app id should match")
    assert(app.cmd == "echo test", "app should have the specified cmd")
  end)

  it("creates an app with custom options", function()
    local app = plugin.register_app("test_app_opts", "<leader>tao", "lazygit", { width = 0.9 })
    assert(app ~= nil, "register_app should return a terminal object")
    assert(app.cmd == "lazygit", "app should have the specified cmd")
  end)
end)

describe("set_timeout", function()
  it("sets a valid timeout", function()
    plugin.set_timeout(200)
    assert(config.timeout == 200, "timeout should be updated")
  end)

  it("ignores invalid timeout", function()
    local original = config.timeout
    plugin.set_timeout("invalid")
    assert(config.timeout == original, "timeout should not change with invalid input")
  end)

  it("ignores nil timeout", function()
    local original = config.timeout
    plugin.set_timeout(nil)
    assert(config.timeout == original, "timeout should not change with nil input")
  end)
end)

describe("list_terminals", function()
  it("returns a list of registered terminals", function()
    local terminals = plugin.list_terminals()
    assert(type(terminals) == "table", "list_terminals should return a table")
    assert(#terminals > 0, "list_terminals should return registered terminals")
  end)
end)
